services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank
    ports:
      - '5432:5432'
    volumes: 
      - ./db/scripts/00_setup.sql:/docker-entrypoint-initdb.d/00_setup.sql
      - ./db/scripts/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/scripts/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql